spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lagou_training?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root 
 mail:
    default-encoding: UTF-8
    host: smtp.office365.com
    username: kabibear@outlook.com
    password: Kabikabi
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true 
